// frontend/src/components/LoadingSpinner.vue
<template>
	<div class="flex items-center justify-center">
		<div class="relative">
			<div class="w-12 h-12 rounded-full absolute border-4 border-solid border-gray-200"></div>
			<div
				class="w-12 h-12 rounded-full animate-spin absolute border-4 border-solid border-transparent"
				:class="[colorClass, 'border-t-current']"
			></div>
		</div>
		<div v-if="text" class="ml-4 text-lg">{{ text }}</div>
	</div>
</template>

<script setup lang="ts">
interface Props {
	text?: string;
	colorClass?: string;
}

defineProps<Props>();
</script>

// frontend/src/components/LoadingSpinner.tsx
import type React from "react"

interface LoadingSpinnerProps {
  text?: string
  colorClass?: string
}

const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({ text, colorClass = "border-amber-500" }) => {
  return (
    <div className="flex items-center justify-center">
      <div className="relative">
        <div className="w-12 h-12 rounded-full absolute border-4 border-solid border-gray-200"></div>
        <div
          className={`w-12 h-12 rounded-full animate-spin absolute border-4 border-solid border-transparent ${colorClass} border-t-current`}
        ></div>
      </div>
      {text && <div className="ml-4 text-lg">{text}</div>}
    </div>
  )
}

export default LoadingSpinner
