// frontend/src/App.tsx
"use client";

import type React from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { ThemeProvider } from "./context/ThemeContext";
import { ErrorProvider } from "./context/ErrorContext";
import { CocktailProvider } from "./context/CocktailContext";
import { LanguageProvider } from "./context/LanguageContext";
import ThemeToggle from "./components/ThemeToggle";
import LanguageSelector from "./components/LanguageSelector";
import ErrorAlert from "./components/ErrorAlert";
import Home from "./pages/Home";
import Questions from "./pages/Questions";
import CocktailRecommendation from "./pages/CocktailRecommendation";
import { useError } from "./context/ErrorContext";
import { useTheme } from "./context/ThemeContext";

// Layout component to wrap all pages
const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	const { message, clearError } = useError();
	const { theme } = useTheme();

	// 计算属性：主题相关样式
	const themeClasses =
		theme === "dark"
			? "bg-gradient-to-b from-gray-950 to-gray-900 text-white"
			: "bg-gradient-to-b from-amber-50 to-white text-gray-900";

	// 计算属性：头部样式
	const headerClasses = theme === "dark" ? "border-gray-800 bg-black/90" : "border-amber-100 bg-white/90";

	// 计算属性：页脚样式
	const footerClasses =
		theme === "dark" ? "border-gray-800 bg-black/30 backdrop-blur-sm" : "border-amber-100 bg-white/80 backdrop-blur-sm";

	// 计算属性：边框颜色
	const borderColorClass = theme === "dark" ? "border-gray-800" : "border-amber-100";

	// 计算属性：文本颜色
	const textColorClass = theme === "dark" ? "text-white" : "text-gray-900";

	return (
		<div className={`min-h-screen transition-colors duration-300 flex flex-col ${themeClasses}`}>
			<header
				className={`sticky top-0 z-10 border-b backdrop-blur-lg transition-colors duration-300 shadow-md ${headerClasses}`}
			>
				<div className="container flex h-16 items-center justify-between">
					<a href="/" className="flex items-center gap-2 font-bold text-xl transition-transform hover:scale-105">
						<div className="w-8 h-8 rounded-full bg-gradient-to-r from-amber-500 to-pink-500 flex items-center justify-center shadow-lg">
							<span className="text-white text-sm">🍹</span>
						</div>
						<span className="bg-gradient-to-r from-amber-500 to-pink-500 bg-clip-text text-transparent">
							MoodShaker
						</span>
					</a>
					<div className="flex items-center gap-4">
						<LanguageSelector />
						<ThemeToggle />
					</div>
				</div>
			</header>

			<ErrorAlert message={message} onClose={clearError} />

			<main className="flex-1 relative">{children}</main>

			{/* 增强的页脚 */}
			<footer className={`border-t transition-colors duration-300 py-12 ${footerClasses}`}>
				<div className="container">
					<div className="grid grid-cols-1 md:grid-cols-3 gap-8">
						{/* 品牌信息 */}
						<div className="md:col-span-1">
							<div className="flex items-center gap-2 mb-4">
								<div className="w-10 h-10 rounded-full bg-gradient-to-r from-amber-500 to-pink-500 flex items-center justify-center shadow-lg">
									<span className="text-white text-sm">🍹</span>
								</div>
								<span className="font-bold text-xl bg-gradient-to-r from-amber-500 to-pink-500 bg-clip-text text-transparent">
									MoodShaker
								</span>
							</div>
							<p className="text-sm text-gray-400 mb-4">找到适合您心情的鸡尾酒，让每一次品尝都成为难忘的体验。</p>
							<div className="flex space-x-4">
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="20"
										height="20"
										fill="currentColor"
										viewBox="0 0 16 16"
									>
										<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
									</svg>
								</a>
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="20"
										height="20"
										fill="currentColor"
										viewBox="0 0 16 16"
									>
										<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
									</svg>
								</a>
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="20"
										height="20"
										fill="currentColor"
										viewBox="0 0 16 16"
									>
										<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
									</svg>
								</a>
							</div>
						</div>

						{/* 联系我们 */}
						<div className="md:col-span-1 md:col-start-3">
							<h3 className={`font-bold text-lg mb-4 ${textColorClass}`}>联系我们</h3>
							<ul className="space-y-2">
								<li className="flex items-center text-gray-400">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										className="h-5 w-5 mr-2 text-amber-500"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
									>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth="2"
											d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
										/>
									</svg>
									contact@moodshaker.com
								</li>
								<li className="flex items-center text-gray-400">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										className="h-5 w-5 mr-2 text-amber-500"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
									>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth="2"
											d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
										/>
									</svg>
									+86 123 4567 8910
								</li>
								<li className="flex items-center text-gray-400">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										className="h-5 w-5 mr-2 text-amber-500"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
									>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth="2"
											d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
										/>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth="2"
											d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
										/>
									</svg>
									上海市浦东新区张江高科技园区
								</li>
							</ul>
						</div>
					</div>

					<div className={`mt-10 pt-8 border-t text-center text-sm text-gray-400 ${borderColorClass}`}>
						<div className="flex flex-col md:flex-row justify-between items-center">
							<p>© 2024 MoodShaker. 保留所有权利。</p>
							<div className="flex space-x-6 mt-4 md:mt-0">
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">
									隐私政策
								</a>
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">
									使用条款
								</a>
								<a href="#" className="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">
									Cookie 政策
								</a>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>
	);
};

// Main App component
const AppContent: React.FC = () => {
	return (
		<Router>
			<Routes>
				<Route path="/" element={<Home />} />
				<Route path="/questions" element={<Questions />} />
				<Route path="/cocktail/recommendation" element={<CocktailRecommendation />} />
			</Routes>
		</Router>
	);
};

// App with all providers
const App: React.FC = () => {
	return (
		<ThemeProvider>
			<ErrorProvider>
				<CocktailProvider>
					<LanguageProvider>
						<Layout>
							<AppContent />
						</Layout>
					</LanguageProvider>
				</CocktailProvider>
			</ErrorProvider>
		</ThemeProvider>
	);
};

export default App;

// frontend/src/App.vue
<template>
	<div class="min-h-screen transition-colors duration-300" :class="themeClasses">
		<header
			class="sticky top-0 z-10 border-b backdrop-blur-lg transition-colors duration-300 shadow-md"
			:class="headerClasses"
		>
			<div class="container flex h-16 items-center justify-between">
				<router-link
					to="/"
					class="font-bold text-xl bg-gradient-to-r from-amber-500 to-pink-500 bg-clip-text text-transparent transition-transform hover:scale-105"
				>
					{{ $t("MoodShaker") }}
				</router-link>
				<div class="flex items-center gap-4">
					<LanguageSelector />
					<ThemeToggle />
				</div>
			</div>
		</header>

		<ErrorAlert :message="errorStore.message" @close="errorStore.clearError()" />

		<main class="flex-1 relative">
			<router-view v-slot="{ Component }">
				<transition name="fade" mode="out-in">
					<component :is="Component" />
				</transition>
			</router-view>
		</main>

		<!-- Added footer -->
		<footer class="border-t transition-colors duration-300 py-8" :class="footerClasses">
			<div class="container">
				<div class="flex flex-col md:flex-row justify-between items-center">
					<div class="mb-4 md:mb-0">
						<div class="font-bold text-lg bg-gradient-to-r from-amber-500 to-pink-500 bg-clip-text text-transparent">
							MoodShaker
						</div>
						<p class="text-sm text-gray-400 mt-1">找到适合您心情的鸡尾酒</p>
					</div>
					<div class="flex space-x-6">
						<a href="#" class="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">关于我们</a>
						<a href="#" class="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">联系方式</a>
						<a href="#" class="text-gray-400 hover:text-amber-500 transition-colors whitespace-nowrap">隐私政策</a>
					</div>
				</div>
				<div class="mt-6 pt-6 border-t text-center text-sm text-gray-400" :class="borderColorClass">
					© 2024 MoodShaker. 保留所有权利。
				</div>
			</div>
		</footer>
	</div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { storeToRefs } from "pinia";
import { useThemeStore } from "@/stores/theme";
import { useErrorStore } from "@/stores/error";
import ThemeToggle from "@/components/ThemeToggle.vue";
import LanguageSelector from "@/components/LanguageSelector.vue";
import ErrorAlert from "@/components/ErrorAlert.vue";

const themeStore = useThemeStore();
const errorStore = useErrorStore();
const { theme } = storeToRefs(themeStore);

// 计算属性：主题相关样式
const themeClasses = computed(() => {
	const darkTheme = theme.value === "dark";
	return {
		"bg-gradient-to-b from-black to-gray-900 text-white": darkTheme,
		"bg-gradient-to-b from-amber-50 to-white text-gray-900": !darkTheme,
	};
});

// 计算属性：头部样式
const headerClasses = computed(() => {
	const darkTheme = theme.value === "dark";
	return {
		"border-gray-800 bg-black/90": darkTheme,
		"border-amber-100 bg-white/90": !darkTheme,
	};
});

// 计算属性：页脚样式
const footerClasses = computed(() => {
	const darkTheme = theme.value === "dark";
	return {
		"border-gray-800 bg-black/30 backdrop-blur-sm": darkTheme,
		"border-amber-100 bg-white/80 backdrop-blur-sm": !darkTheme,
	};
});

// 计算属性：边框颜色
const borderColorClass = computed(() => {
	const darkTheme = theme.value === "dark";
	return {
		"border-gray-800": darkTheme,
		"border-amber-100": !darkTheme,
	};
});
</script>

<style>
.fade-enter-active,
.fade-leave-active {
	transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
	opacity: 0;
}

/* 确保所有按钮文字不换行 */
button,
a {
	white-space: nowrap;
}
</style>
