// frontend/components/pages/Home.tsx
"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { ArrowRight, History } from "lucide-react"
import { useTheme } from "@/context/ThemeContext"
import { useLanguage } from "@/context/LanguageContext"

// Import cocktail images
const cocktailImages = {
  mojito: "/vibrant-mojito.png",
  margarita: "/vibrant-margarita.png",
  cosmopolitan: "/city-lights-cocktail.png",
}

export default function Home() {
  const { theme } = useTheme()
  const { t } = useLanguage()
  const [hasSavedSession, setHasSavedSession] = useState(false)
  const [currentCocktailIndex, setCurrentCocktailIndex] = useState(0)

  // Featured cocktails for the hero section
  const featuredCocktails = [
    {
      name: "莫吉托",
      englishName: "Mojito",
      description: "清新薄荷与青柠的完美结合",
      image: cocktailImages.mojito,
    },
    {
      name: "玛格丽特",
      englishName: "Margarita",
      description: "经典龙舌兰鸡尾酒，酸甜平衡",
      image: cocktailImages.margarita,
    },
    {
      name: "大都会",
      englishName: "Cosmopolitan",
      description: "时尚优雅的蔓越莓伏特加鸡尾酒",
      image: cocktailImages.cosmopolitan,
    },
  ]

  useEffect(() => {
    // 检查是否有保存的会话
    if (typeof window !== "undefined") {
      const answers = localStorage.getItem("moodshaker-answers")
      setHasSavedSession(!!answers)
    }

    // Rotate featured cocktails
    const interval = setInterval(() => {
      setCurrentCocktailIndex((prev) => (prev + 1) % featuredCocktails.length)
    }, 5000)

    return () => clearInterval(interval)
  }, [])

  // 确定主题相关的样式
  const bgClass = theme === "dark" ? "bg-gray-900" : "bg-gray-50"
  const textClass = theme === "dark" ? "text-white" : "text-gray-900"
  const cardClass = theme === "dark" ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
  const mutedTextClass = theme === "dark" ? "text-gray-400" : "text-gray-600"

  return (
    <div className={`${bgClass} ${textClass}`}>
      {/* Hero Section */}
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            {/* Left column - Text content */}
            <div>
              <h1 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-amber-500 to-pink-500 bg-clip-text text-transparent">
                {t("home.title")}
              </h1>
              <p className={`text-lg mb-8 ${mutedTextClass}`}>{t("home.subtitle")}</p>

              {/* Session buttons */}
              {hasSavedSession ? (
                <div className={`p-6 border rounded-xl mb-6 ${cardClass}`}>
                  <div className="flex items-center mb-4">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mr-3">
                      <History className="h-5 w-5 text-amber-500" />
                    </div>
                    <h3 className="text-xl font-bold">{t("home.savedSession")}</h3>
                  </div>
                  <p className={`mb-5 ${mutedTextClass}`}>{t("home.savedSessionDesc")}</p>
                  <div className="flex flex-col sm:flex-row gap-3">
                    <Link
                      href="/questions"
                      className="px-5 py-3 bg-gradient-to-r from-amber-500 to-pink-500 hover:from-amber-600 hover:to-pink-600 text-white rounded-full shadow-lg transition-all duration-300 hover:scale-105 text-center"
                    >
                      {t("home.continue")}
                    </Link>
                    <Link
                      href="/questions?new=true"
                      className={`px-5 py-3 bg-white/10 hover:bg-white/20 border border-white/20 rounded-full transition-all duration-300 ${textClass} text-center`}
                    >
                      {t("home.new")}
                    </Link>
                  </div>
                </div>
              ) : (
                <Link
                  href="/questions"
                  className="px-8 py-4 text-lg font-medium bg-gradient-to-r from-amber-500 to-pink-500 hover:from-amber-600 hover:to-pink-600 text-white rounded-full shadow-lg transition-all duration-300 hover:scale-105 flex items-center inline-flex"
                >
                  {t("home.start")}
                  <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </Link>
              )}
            </div>

            {/* Right column - Featured cocktail */}
            <div className="relative h-[400px] md:h-[500px]">
              {featuredCocktails.map((cocktail, index) => (
                <div
                  key={index}
                  className={`absolute inset-0 transition-all duration-1000 ${
                    index === currentCocktailIndex
                      ? "opacity-100 translate-y-0"
                      : "opacity-0 translate-y-8 pointer-events-none"
                  }`}
                >
                  <div className="relative h-full">
                    <div className="absolute -inset-4 bg-gradient-to-r from-amber-500/20 to-pink-500/20 rounded-full blur-xl"></div>
                    <img
                      src={cocktail.image || "/placeholder.svg"}
                      alt={cocktail.name}
                      className="relative rounded-3xl shadow-2xl w-full h-full object-cover"
                    />
                    <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/80 to-transparent rounded-b-3xl">
                      <h3 className="text-2xl font-bold text-white">{cocktail.name}</h3>
                      <p className="text-sm text-gray-300">{cocktail.englishName}</p>
                      <p className="text-white/80 mt-2">{cocktail.description}</p>
                    </div>
                  </div>
                </div>
              ))}

              {/* Navigation dots */}
              <div className="absolute -bottom-8 left-1/2 transform -translate-x-1/2 flex space-x-2">
                {featuredCocktails.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentCocktailIndex(index)}
                    className={`w-3 h-3 rounded-full transition-all ${
                      index === currentCocktailIndex
                        ? "bg-gradient-to-r from-amber-500 to-pink-500 scale-125"
                        : "bg-white/30"
                    }`}
                    aria-label={`View cocktail ${index + 1}`}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className={`py-16 ${theme === "dark" ? "bg-gray-800/50" : "bg-gray-100"}`}>
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-amber-400 to-pink-500 bg-clip-text text-transparent">
              为什么选择 MoodShaker?
            </h2>
            <p className={`text-lg max-w-2xl mx-auto ${mutedTextClass}`}>
              我们的智能推荐系统会根据您的喜好和心情，为您找到完美的鸡尾酒
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div
              className={`border rounded-xl p-6 text-left transition-transform duration-300 hover:scale-105 ${cardClass}`}
            >
              <div className="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4">
                <span className="text-2xl">🧪</span>
              </div>
              <h3 className="text-xl font-bold mb-2">{t("home.feature1.title")}</h3>
              <p className={mutedTextClass}>{t("home.feature1.description")}</p>
            </div>
            <div
              className={`border rounded-xl p-6 text-left transition-transform duration-300 hover:scale-105 ${cardClass}`}
            >
              <div className="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4">
                <span className="text-2xl">📝</span>
              </div>
              <h3 className="text-xl font-bold mb-2">{t("home.feature2.title")}</h3>
              <p className={mutedTextClass}>{t("home.feature2.description")}</p>
            </div>
            <div
              className={`border rounded-xl p-6 text-left transition-transform duration-300 hover:scale-105 ${cardClass}`}
            >
              <div className="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4">
                <span className="text-2xl">✨</span>
              </div>
              <h3 className="text-xl font-bold mb-2">{t("home.feature3.title")}</h3>
              <p className={mutedTextClass}>{t("home.feature3.description")}</p>
            </div>
          </div>
        </div>
      </section>

      {/* Popular Cocktails Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-amber-400 to-pink-500 bg-clip-text text-transparent">
              热门鸡尾酒
            </h2>
            <p className={`text-lg max-w-2xl mx-auto ${mutedTextClass}`}>探索我们用户最喜爱的鸡尾酒</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {featuredCocktails.map((cocktail, index) => (
              <div
                key={index}
                className={`border rounded-xl overflow-hidden transition-transform duration-300 hover:scale-105 ${cardClass}`}
              >
                <div className="h-48">
                  <img
                    src={cocktail.image || "/placeholder.svg"}
                    alt={cocktail.name}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-1">{cocktail.name}</h3>
                  <p className="text-sm text-gray-400 mb-3">{cocktail.englishName}</p>
                  <p className={mutedTextClass}>{cocktail.description}</p>
                  <Link
                    href="/questions"
                    className="mt-4 w-full py-2 bg-gradient-to-r from-amber-500/20 to-pink-500/20 hover:from-amber-500/30 hover:to-pink-500/30 text-white border border-white/10 rounded-full transition-all duration-300 block text-center"
                  >
                    获取配方
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}

// frontend/src/views/Home.vue
<template>
	<div class="flex-1 relative">
		<!-- Enhanced decorative elements with animation -->
		<div class="absolute inset-0 overflow-hidden opacity-30 pointer-events-none">
			<div
				class="absolute -top-10 -right-10 w-80 h-80 bg-amber-500 rounded-full blur-3xl animate-pulse"
				style="animation-duration: 8s"
			></div>
			<div
				class="absolute top-1/3 -left-10 w-80 h-80 bg-pink-500 rounded-full blur-3xl animate-pulse"
				style="animation-duration: 10s; animation-delay: 2s"
			></div>
			<div
				class="absolute -bottom-10 right-1/4 w-80 h-80 bg-purple-500 rounded-full blur-3xl animate-pulse"
				style="animation-duration: 12s; animation-delay: 4s"
			></div>
		</div>

		<section class="container py-16 md:py-28 lg:py-36 relative" style="margin: 0 auto">
			<div class="mx-auto flex max-w-[980px] flex-col items-center gap-6 text-center">
				<div class="inline-block mb-6 p-3 bg-white/5 backdrop-blur-sm rounded-full shadow-xl">
					<div
						class="w-24 h-24 rounded-full bg-gradient-to-tr from-amber-500 to-pink-500 flex items-center justify-center shadow-lg shadow-pink-500/20"
					>
						<span class="text-3xl">🍹</span>
					</div>
				</div>
				<h1
					class="text-4xl font-bold leading-tight tracking-tighter md:text-6xl lg:text-7xl bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent"
				>
					找到适合您心情的鸡尾酒
				</h1>
				<p class="max-w-[700px] text-xl text-gray-300 md:text-2xl leading-relaxed">
					通过回答几个简单问题，让我们为您推荐完美的鸡尾酒
				</p>

				<!-- 会话选择区域 -->
				<div class="w-full sm:w-auto mt-10 flex flex-col items-center">
					<div
						v-if="hasSavedSession"
						class="w-full mb-6 backdrop-blur-sm bg-white/5 border border-white/10 rounded-2xl p-6 max-w-md"
					>
						<div class="flex items-center mb-4">
							<div
								class="w-10 h-10 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mr-3"
							>
								<History class="h-5 w-5 text-amber-500" />
							</div>
							<h3 class="text-xl font-bold text-white">检测到未完成的问卷</h3>
						</div>
						<p class="text-gray-300 mb-5">您有一个未完成的鸡尾酒推荐问卷。您想继续之前的问卷还是开始一个新的？</p>
						<div class="flex flex-col sm:flex-row gap-3">
							<button
								@click="continueSession"
								class="flex-1 px-5 py-3 bg-gradient-to-r from-amber-500 to-pink-500 hover:from-amber-600 hover:to-pink-600 text-white rounded-full shadow-lg shadow-pink-500/20 transition-all duration-300 hover:scale-105 whitespace-nowrap"
							>
								继续上次问卷
							</button>
							<button
								@click="startNewSession"
								class="flex-1 px-5 py-3 bg-white/10 hover:bg-white/20 text-white border border-white/20 rounded-full transition-all duration-300 whitespace-nowrap"
							>
								开始新问卷
							</button>
						</div>
					</div>

					<!-- 如果没有保存的会话，只显示开始按钮 -->
					<button
						v-if="!hasSavedSession"
						@click="startNewSession"
						class="w-full sm:w-auto px-10 py-4 text-lg font-medium bg-gradient-to-r from-amber-500 to-pink-500 hover:from-amber-600 hover:to-pink-600 text-white border-0 shadow-xl shadow-pink-500/30 rounded-full flex items-center justify-center transition-all duration-300 hover:scale-105 group whitespace-nowrap"
					>
						开始探索 <ArrowRight class="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
					</button>
				</div>

				<!-- Added feature highlights -->
				<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mt-16 w-full">
					<div
						class="backdrop-blur-sm bg-white/5 border border-white/10 rounded-2xl p-6 text-left shadow-xl transition-transform duration-300 hover:scale-105 hover:bg-gradient-to-br hover:from-white/5 hover:to-white/10"
					>
						<div
							class="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4"
						>
							<span class="text-2xl">🧪</span>
						</div>
						<h3 class="text-xl font-bold mb-2 whitespace-nowrap">个性化推荐</h3>
						<p class="text-gray-300">根据您的口味偏好和心情，为您量身定制鸡尾酒推荐</p>
					</div>
					<div
						class="backdrop-blur-sm bg-white/5 border border-white/10 rounded-2xl p-6 text-left shadow-xl transition-transform duration-300 hover:scale-105 hover:bg-gradient-to-br hover:from-white/5 hover:to-white/10"
					>
						<div
							class="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4"
						>
							<span class="text-2xl">📝</span>
						</div>
						<h3 class="text-xl font-bold mb-2 whitespace-nowrap">详细配方</h3>
						<p class="text-gray-300">获取完整的配料清单和制作步骤，轻松在家调制美味鸡尾酒</p>
					</div>
					<div
						class="backdrop-blur-sm bg-white/5 border border-white/10 rounded-2xl p-6 text-left shadow-xl transition-transform duration-300 hover:scale-105 hover:bg-gradient-to-br hover:from-white/5 hover:to-white/10"
					>
						<div
							class="w-12 h-12 rounded-full bg-gradient-to-r from-amber-500/20 to-pink-500/20 flex items-center justify-center mb-4"
						>
							<span class="text-2xl">✨</span>
						</div>
						<h3 class="text-xl font-bold mb-2 whitespace-nowrap">创意灵感</h3>
						<p class="text-gray-300">发现新的口味组合和创意调酒技巧，提升您的调酒体验</p>
					</div>
				</div>
			</div>
		</section>
	</div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { ArrowRight, History } from "lucide-vue-next";

const router = useRouter();
const hasSavedSession = ref(false);
const savedAnswers = ref(null); // Initialize savedAnswers

onMounted(() => {
	// 检查是否有保存的会话
	if (typeof window !== "undefined") {
		savedAnswers.value = localStorage.getItem("moodshaker-answers");
		hasSavedSession.value = !!savedAnswers.value;
	}
});

// 继续上次会话
const continueSession = () => {
	router.push("/questions");
};

// 开始新会话
const startNewSession = () => {
	router.push("/questions?new=true");
};
</script>

<style scoped>
/* 确保所有按钮文字不换行 */
button {
	white-space: nowrap;
}
</style>
